### ISSUE TITLE
Create dummy buttons

### ISSUE THREAD

**Issue by julius-kress** [BP-TPSE-Projektgruppe-80/NaPyTau#6]
# Add basic buttons to the GUI

The GUI should have the following buttons:
- [x] **File** for opening and saving files
- [x] **View** for light and darkmode
- [x] **Polynomials** for choosing the number of used polynomials, as well as equidistant or exponential distance
- [x] **Alpha calculation** for choosing between the options of calculating alpha (Sum Ratio or Weighted Mean)

Unless otherwise possible, the buttons serve as dummies, functionality should be implemented later on.

Additionaly to that two rows of buttons should be implemented.
One for choosing which data points to use for the fit, the other one for choosing which data points to use for the calculation of &tau; and &Delta; &tau;.

**Comment by Benedikt-Brunner** [comment]
I did a quick test of this, everything looks fine to me, however there is a bug where when one deletes the value in the input field, an error is thrown on the Terminal. This isn't tragic, since it does not affect the UI, however we should understand and fix it, i will create a follow up Issue.

**Comment by Benedikt-Brunner** [comment]
I created the follow up issue: https://github.com/BP-TPSE-Projektgruppe-80/NaPyTau/issues/23
